### ISSUE TITLE
Imager and css not working after installation

### ISSUE THREAD

**Issue by nurzaly** [LaravelDaily/Laravel-Demo-Courses-Enrollment#1]
![image](https://user-images.githubusercontent.com/11963465/76097463-b7519680-6002-11ea-9aac-4fd55addc443.png)

**Comment by PovilasKorop** [comment]
@nurzaly there was an issue with CoreUI theme: https://quickadminpanel.com/blog/for-customers-replace-coreui-theme-to-use-v2-1-16-instead-of-v3-0/

**Comment by aysnet1** [comment]
Run the command

> php artisan storage:link
If url images not working 👆
